[version info]
# major.feature[.patch]
installed version: 1.10.3
latest release: 2.0.0
# This update includes: (message)
major update: Complete rewrite and update to 1.59
feature update: Vehicle search boxes, updated W900 support and 1 new language
patch update: Support for the Wielton Trailer Pack DLC
