[vehicle info]
vehicle path: man.tg3
alt uvset: false
name: MAN TGX (TG3)
trailer: false
mod: false
mod author: Gloover
mod link workshop: 
mod link forums: 
mod link trucky: 
mod link author site: 
bus mod: false
bus door workaround: false
uses accessories: true
accessories: Badge;Beacon Mount;Detectors;Grill;Plate;Seat;Corner Deflectors;Door Steps;Exhaust;Filter;Front Bumper;Front Fender;Front Fender - Duty;Front Fender - Standard;Mirrors;Sideskirts

[cabins]
separate paintjobs: true
a: Cabin A (GX);gx
; b: Cabin B (GM);gm
; c: Cabin C (GN);gn

[Badge]
badge_a.tgx_18
badge_b.hp330
badge_b.hp360
badge_b.hp400
badge_b.hp430
badge_b.hp470
badge_b.hp510
badge_b.hp540
badge_b.hp580
badge_b.hp640
badge_c.d38
badge_c.indi
badge_c.none
f_badge.chrome

[Beacon Mount]
beacon.mount_gx

[Detectors]
b_detector.paint
b_detector.plastic

[Grill]
b_grill.indi_c

[Plate]
codrv_plate.plate
drv_plate.plate 

[Seat]
codrv_seat.individual

[Corner Deflectors]
cor_def.paint

[Door Steps]
doorstep.stock

[Exhaust]
exhaust_l.id_p_short

[Filter]
filter.plastic


[Front Bumper]
f_bumper.plastic_std

[Front Fender]
f_fender_cab.paint
f_fender_cab.plastic

[Front Fender - Duty]
f_fender_chs.pnt_duty
f_fender_chs.pls_duty

[Front Fender - Standard]
f_fender_chs.pnt_std
f_fender_chs.pls_std

[Mirrors]
mirror.cam_pnt
mirror.cam_pnt_gn
mirror.pnt_pla
mirror.pnt_pla_bs

[Sideskirts]
sideskirt.4x2
sideskirt.4x2_e
sideskirt.4x2_p
sideskirt.4x2_p_e
sideskirt.fender_p
sideskirt.fender_p_e
sideskirt.fender_s
sideskirt.fender_s_e
